servers:
  - host: "127.0.0.1"   # Server hostname or IP (required)
    username: "admin"           # SSH username (required)
    password: "secret123"       # SSH password (optional, not recommended)
    # key_file: "/path/to/key"  # SSH private key path (alternative to password)
    commands:                   # List of commands to execute (required)
      - "uptime"
      - "df -h"